apiVersion: v1
kind: Service
metadata:
  name: iban-validator-backend
  namespace: iban-validator
spec:
  type: ClusterIP
  selector:
    app: iban-validator-backend
  ports:
    - name: http
      port: 80
      targetPort: http
